### ISSUE TITLE
how do I change queue's counter limit?

### ISSUE THREAD

**Issue by ks** [esl/jobs#17]
Hi,

with:

(dev1@xmd)20> C = jobs:add_counter(c, [{limit, 10}]).
ok
(dev1@xmd)21> jobs:info(counters).
[{cr,[{name,c},
      {increment,1},
      {value,0},
      {rate,{rate,[{limit,10},
                   {preset_limit,10},
                   {interval,infinity},
                   {modifiers,[]},
                   {active_modifiers,[]}]}},
      {owner,undefined},
      {queues,[]},
      {shared,true}]}]

how do I create a queue like, Q = jobs:add_queue(q, [{regulators, [{counter, c}]}]), which will react to changes of counter c limits, e.g. when changing counter c limit like,  jobs:modify_counter(c, [{limit, 100}]), 100 jobs from Q can run concurrently?

Thanks

**Comment by uwiger** [comment]
You should be able to do that with `jobs:add_queue(q, [{counter, [{name, c}]}])`.

**Comment by ks** [comment]
Thanks!
